Feature task list
georgiiio/todo-list pull request #1
Opened 2022-10-27 17:20 UTC by georgiiio

2022-10-27 17:38 UTC, polyakov713 commented on task-list.html
> +</html>
Нао добавить пустую строку в конец. 
https://qna.habr.com/q/1094540

2022-10-27 17:38 UTC, polyakov713 commented on task-list.html
> +         <h4>Future task list</h4>
Непонятного назначения отступ)

2022-10-27 17:38 UTC, polyakov713 commented on task-list.html
> +      <li>First position</li>
Сверху отступ в 4 пробела, а тут - в два. Надо определиться) В каждой компании свои стандарты. Но чаще я встречал в 2. Это по началу непривычно, но за пару дней привыкаешь

2022-10-27 17:38 UTC, polyakov713 commented on task-list.html
> +      <li>Second position</li>
Я бы для примера написал какие-то похожие на реальные задачи, которые человек может внести в свой список дел (ToDO List). Типа "Покормить собак", "Сходить за молоком", "Сделать домашку по английскому"

2022-10-27 17:38 UTC, polyakov713 commented on task-list.html
> +    <meta name="viewport" content="width=device-width, initial-scale=1.0">
JFYI: Про этот метатег любят на собеседованиях спрашивать. Погугли. Если не поймешь - разберемся вместе

2022-10-27 17:38 UTC, polyakov713 commented on task-list.html
> +<!DOCTYPE html>
Про доктайп тоже баянистый вопрос на собеседованиях

2022-10-27 17:39 UTC, polyakov713 commented
Отлично, только где стили? И почему создал отдельный файл, а не сверстал внутри уже существующего index.html?)

2022-10-28 14:31 UTC, polyakov713 requested changes

2022-10-28 14:31 UTC, polyakov713 commented on index.html
> +<h4>Future task list</h4>
не хватает отступа от body

2022-10-28 14:31 UTC, polyakov713 commented on assets/style.css
> +}
Базовые общие стили, которые вышитый, лучше вынести в отдельный css-файл. Какой-нибудь reset.css

2022-10-28 14:31 UTC, polyakov713 commented on assets/style.css
> +    background: #fff;
отступ 4 пробела. Загубил как настроить Отступы для vscode глобально. ЧТоб он для всех файлов применял

2022-10-28 14:31 UTC, polyakov713 commented on assets/style.css
> +    width: 100vw;
body по-умолчанию и так на всю ширину экрана будет. НЕт смысла в этом стиле. Про высоту не уверен, возможно - тоже.

2022-10-28 14:31 UTC, polyakov713 commented on assets/style.css
> +
У тебя какое-то рандомное число пустых строк между блоками. То 4, то 2, то 1. Обычно везде делают 1. На худой конец - комментам и разбивают на логические части. Но тогда уж лучше отдельный файл создать. Тем более есть css-импорты (почитай, что это)

2022-10-28 14:31 UTC, polyakov713 commented on assets/style.css
> +@import url(https://fonts.googleapis.com/css?family=Rubik+One&subset=latin,cyrillic);
Шрифт лучше самой первой строкой импортировать

2022-10-28 14:31 UTC, polyakov713 commented on assets/style.css
> +  display: table;
Это для чего?)

2022-10-28 14:31 UTC, polyakov713 commented on index.html
> +  <div class="list-head">
элементы, в которых есть инпуты и кнопки и из которых забираются какие-то данные, называются формы. И есть сецилаьный тег from. Я бы его заюзал и класс переназвал

2022-10-28 14:31 UTC, polyakov713 commented on index.html
> +    <input type="text" class="entered-list">
В разработке часто обращают внимание на нейминг. Вещи должны быть названы так, чтобы тому, кто читает, было понятно, что это и что оно делает. `entered-list` - введенный список. Но это же не список) Это инпут для ввода названия таска. Я бы назвал task-title или что-то подобное

2022-10-28 14:31 UTC, polyakov713 commented on index.html
> +    <button class="add-list">Add</button>
МОжет лучше add-task-button?

2022-10-28 14:31 UTC, polyakov713 commented on index.html
> +    <!--<div class="item">
а куда список делся?) Был же тут)

2022-10-28 14:31 UTC, polyakov713 commented on index.html
> +<script src="js/app.js"></script>
Скрипты в конце boy - наследние прошлого. Сейчас их можно класть в шапку рядом со стилями, но надо юзать async или defer атрибуты (почитай про них тоже. ТОже кстати любят спрашивать)

2022-10-28 14:31 UTC, polyakov713 commented on assets/style.css
>  }
пустую строку в конце забыл

2022-10-28 14:31 UTC, polyakov713 commented on js/app.js
> +let input = document.querySelector('.entered-list');
Для идентификации уникального элемента JS-ом лучше айтишники юзать. Классы - они больше для стилей. Ну или если у тебя много таких элементов, то собрать их массив через document.querySelectorAll

2022-10-28 14:31 UTC, polyakov713 commented on js/app.js
> +    if(input.value.trim() !== 0 ){
input.value.trim() вроде возвращает строку. В худшем случае - пустую строку ''
Она никогда не будет равна 0. СОответственно, у тебя всегда будет else

2022-10-28 14:31 UTC, polyakov713 commented on js/app.js
> +input.addEventListener('keyup', () => {
Ты хочешь следить за тем, ведено что-то в инпут или нет? Тогда лучше заюзай событие change. Оно больше по смыслу подходит

2022-10-28 14:31 UTC, polyakov713 commented on js/app.js
> +addBtn.addEventListener('click', () => {
Эту логику я думал оставить на потом. Давай лучше удалим из этого коммита. Это уже не верстка. Пока сверстай, как-будто они уже добавлены 3 штучки. Помнишь я говорил про разделение на отдельные шаги. Надо уметь обстрагивать текущую задачу от всего проекта и не пытаться сделать все сразу

2022-10-28 14:31 UTC, polyakov713 commented on js/app.js
> +})
забыл пустую строку

2022-10-28 14:31 UTC, polyakov713 commented on js/app.js
> +tasks.addEventListener('click', (e) => {
эти два обработчика давай пока тоже уберём. Классы можешь пока просто навесить в разметку как бы для примера. Потом их оживим

2022-10-31 10:10 UTC, georgiiio commented on assets/style.css
> +  display: table;
ты про -webkit ?

2022-10-31 10:58 UTC, polyakov713 approved these changes

2022-10-31 11:03 UTC, merged